---
- name: Add apt repo key
  become: true
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  register: add_repo_key
  ignore_errors: true

- name: Add docker repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    update_cache: yes
    state: present

- name: Install docker package
  become: true
  apt:
      name: docker-ce

- name: Add ubuntu user to docker group
  become: true
  user: name=ubuntu groups=docker append=yes
