---
- name: Clone the repository
  git:
      repo: 'https://github.com/zulcss/qlikme'
      dest: /home/ubuntu/qlikme

- name: Build the docker container
  command: sudo docker build -t demo /home/ubuntu/qlikme/

- name: Run the application
  command: sudo docker run -d -p 5000:5000 demo
